version: '3'

services:
  springapi:
    image: openjdk:10-jre-slim
    container_name: springapi
    ports:
      - 8080:8080
    volumes:
      - ./api-cadastral/target/api-cadastral.jar:/api-cadastral.jar
    command: ["java", "-jar", "api-cadastral.jar"]
    networks:
      - backendNetwork
      - frontendNetwork
      
  angular:
    image: nginx:alpine
    container_name: angular
    ports: 
      - 4200:80
    depends_on:
      - springapi
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app-cadastral/:/usr/share/nginx/html
    networks:
      - frontendNetwork
    

networks:
  backendNetwork:
  frontendNetwork: